# Generated by Django 5.1.3 on 2025-07-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
