# Generated by Django 5.1.3 on 2025-05-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_stock_exchange_stock_last_timestamp_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stock",
            old_name="last_timestamp",
            new_name="latest_price_time",
        ),
        migrations.RenameField(
            model_name="stockprice",
            old_name="timestamp",
            new_name="recorded_at",
        ),
        migrations.RemoveField(
            model_name="stockprice",
            name="last_updated",
        ),
        migrations.AlterField(
            model_name="stock",
            name="exchange",
            field=models.CharField(
                blank=True, default="unknown", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="market_status",
            field=models.CharField(
                blank=True, default="unknown", max_length=50, null=True
            ),
        ),
    ]
