# Generated by Django 5.1.3 on 2025-05-07 17:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_rename_last_timestamp_stock_latest_price_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockprice",
            name="recorded_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
